"use client";

import { useEffect, useState } from "react";
import { useRouter, useParams } from "next/navigation";
import { supabase } from "../../../../lib/supabase";
import { REQUIREMENTS, getStatus, STATUS_LABEL } from "../../../../lib/requirements";
import Nav from "../../../../components/Nav";

export default function Report() {
  const router = useRouter();
  const params = useParams();
  const [property, setProperty] = useState(null);
  const [docs, setDocs] = useState({});
  const [loading, setLoading] = useState(true);
  const today = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

  useEffect(() => {
    (async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) { router.replace("/login"); return; }
      const { data: prop } = await supabase.from("properties").select("*").eq("id", params.id).single();
      setProperty(prop);
      const { data: documents } = await supabase.from("documents").select("*").eq("property_id", params.id);
      const grouped = {};
      (documents || []).forEach((d) => { grouped[d.requirement_key] = d; });
      setDocs(grouped);
      setLoading(false);
    })();
  }, [params.id, router]);

  if (loading) return <div className="min-h-screen flex items-center justify-center"><p className="text-ink/50">Loading...</p></div>;
  if (!property) return <div className="min-h-screen flex items-center justify-center"><p className="text-ink/50">Property not found.</p></div>;

  const score = Math.round(
    (REQUIREMENTS.filter((r) => getStatus(docs[r.key]) === "ok").length / REQUIREMENTS.length) * 100
  );
  const allGood = score === 100;

  return (
    <div className="min-h-screen">
      <div className="print:hidden">
        <Nav />
      </div>
      <div className="max-w-2xl mx-auto px-6 py-10">
        <div className="print:hidden flex items-center justify-between mb-6">
          <button onClick={() => router.push(`/dashboard/${params.id}`)} className="text-sm text-ink/50 hover:text-ink">&larr; Back to property</button>
          <button onClick={() => window.print()} className="bg-forest text-white rounded-lg px-5 py-2.5 text-sm font-semibold hover:bg-forestDeep">
            Print / Save as PDF
          </button>
        </div>

        <div className="bg-white border border-ink/10 rounded-xl p-10 print:border-0 print:p-0">
          <div className="flex items-center justify-between mb-8">
            <div>
              <p className="text-xs font-mono uppercase tracking-wide text-forest mb-1">Compliance report</p>
              <h1 className="text-2xl font-semibold text-forestDeep">{property.name}</h1>
              <p className="text-sm text-ink/45 mt-1">{property.address}</p>
            </div>
            <div className={`text-center rounded-2xl px-6 py-4 ${allGood ? "bg-moss/10" : "bg-gold/10"}`}>
              <div className={`text-3xl font-semibold ${allGood ? "text-forest" : "text-gold"}`}>{score}%</div>
              <div className="text-xs text-ink/45 mt-0.5">compliant</div>
            </div>
          </div>

          <p className="text-sm text-ink/60 mb-8">
            This report reflects the compliance status of the above property as recorded in Tenfa on {today}.
            {allGood
              ? " All tracked requirements are currently on file and valid."
              : " Some tracked requirements are missing, expiring soon, or expired — see below."}
          </p>

          <div className="border border-ink/10 rounded-xl overflow-hidden mb-8">
            {REQUIREMENTS.map((req) => {
              const status = getStatus(docs[req.key]);
              const dot = { ok: "bg-moss", warn: "bg-gold", bad: "bg-red-400", missing: "bg-red-400" }[status];
              return (
                <div key={req.key} className="flex items-center justify-between px-5 py-3 border-b border-ink/10 last:border-b-0 text-sm">
                  <div className="flex items-center gap-3">
                    <span className={`w-2 h-2 rounded-full ${dot}`}></span>
                    {req.name}
                  </div>
                  <span className="text-xs text-ink/50">{STATUS_LABEL[status]}</span>
                </div>
              );
            })}
          </div>

          <div className="text-xs text-ink/40 pt-4 border-t border-ink/10">
            Generated by Tenfa on {today}. This report reflects information entered by the property's landlord
            and is not independently verified. Not a substitute for legal or professional advice.
          </div>
        </div>
      </div>
      <style jsx global>{`
        @media print { body { background: white; } }
      `}</style>
    </div>
  );
}
